name: hotel-management-docker-compose

services:
  mysql:
    container_name: mysql-hotel-management
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - hotel-management-network
    volumes:
      - dbdata:/var/lib/mysql

  hotel-management:
    container_name: hotel-management
    image: faboxrp/hotel-management:latest # Usa la imagen reconstruida
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql-hotel-management
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - hotel-management-network
    volumes:
      - psdata:/var/www/html

networks:
  hotel-management-network:


volumes:
  dbdata:
  psdata:
